//Generated: Sat Dec 12 17:03:10 PST 2020

#define PID_SW_BALL_RETURN 1
#define PID_SW_TILT 2
#define PID_SW_RIGHT_SPINNER 3
#define PID_SW_RIGHT_EXTRA_BALL_LANE 4
#define PID_SW_A 5
#define PID_SW_START 6
#define PID_SW_LEFT_TARGET 7
#define PID_SW_LEFT_SLING_SHOT 8
#define PID_SW_B 9
#define PID_SW_LEFT_THUMPER_BUMPER 10
#define PID_SW_LEFT_BUMPER 11
#define PID_SW_LEFT_EXTRA_BALL_LANE 12
#define PID_SW_C 13
#define PID_SW_RIGHT_THUMPER_BUMPER 14
#define PID_SW_LEFT_SPINNER 15
#define PID_SW_LEFT_ADVANCED_LANE 16
#define PID_SW_D 17
#define PID_SW_RIGHT_TARGET 18
#define PID_SW_RIGHT_SLING_SHOT 19
#define PID_SW_CENTER_TARGET 20
#define PID_SW_RIGHT_BUMPER 21
#define PID_SW_RIGHT_ADVANCED_LANE 22
#define PID_SW_FLIPPER_LEFT 23
#define PID_SW_FLIPPER_RIGHT 24
